name: Validate codecov.yml

on:
  pull_request:
    files:
      - .github/workflows/validate-codecov.yml
      - codecov.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -X POST --fail-with-body --retry 10 --data-binary @codecov.yml https://codecov.io/validate